### PR TITLE
Added object signatures.

### LINKED ISSUE #43: Add For(Type) to support convention registrations
Thanks for creating RestEase. It looks like exactly what I'm after to replace RestSharp.

I'm writing an Autofac module where I am doing convention based registrations for multiple interfaces that use RestEase. At the point of registration, I am resolving a set of classes that follow a naming convention. I then want to register these with an Autofac container builder. Unfortunately this isn't possible without falling down to reflection calls because RestEase only supports ```For<T>```, however I have ```IEnumerable<Type>``` to work with.

My current implementation is
```
        private void RegisterQueries(ContainerBuilder builder)
        {
            var assemblyTypes = ThisAssembly.GetTypes();
            var configTypes = assemblyTypes
                .Where(x => x.IsAssignableTo<IResolverConfig>() && x.GetTypeInfo().IsClass).ToList();
            var registerWrapperTemplate = typeof(RegisterWrapper<IResolverConfig>).GetGenericTypeDefinition();

            foreach (var configType in configTypes)
            {
                var name = configType.Name.Replace("Config", string.Empty);
                var configInterface = configType.GetTypeInfo().GetInterface("I" + configType.Name);
                var queryTypeName = "I" + name + "LocationQuery";
                var queryType = assemblyTypes.Single(x => x.Name == queryTypeName && x.GetTypeInfo().IsInterface);
                var registerWrapper = registerWrapperTemplate.MakeGenericType(queryType);

                builder.Register(
                    c =>
                    {
                        var config = (IResolverConfig)c.Resolve(configInterface);

                        var wrapper = (IRegisterWrapper)Activator.CreateInstance(registerWrapper);

                        return wrapper.Create(config.Address);
                    }).As(queryType);
            }
        }

        private interface IRegisterWrapper
        {
            object Create(string address);
        }

        private class RegisterWrapper<T> : IRegisterWrapper
        {
            public object Create(string address)
            {
                return RestClient.For<T>(address);
            }
        }
```

If RestEase supported returning object via a Type parameter, this could be streamlined to this
```
        private void RegisterQueries(ContainerBuilder builder)
        {
            var assemblyTypes = ThisAssembly.GetTypes();
            var configTypes = assemblyTypes
                .Where(x => x.IsAssignableTo<IResolverConfig>() && x.GetTypeInfo().IsClass).ToList();

            foreach (var configType in configTypes)
            {
                var name = configType.Name.Replace("Config", string.Empty);
                var configInterface = configType.GetTypeInfo().GetInterface("I" + configType.Name);
                var queryTypeName = "I" + name + "LocationQuery";
                var queryType = assemblyTypes.Single(x => x.Name == queryTypeName);

                builder.Register(
                    c =>
                    {
                        var config = (IResolverConfig)c.Resolve(configInterface);

                        return RestClient.For(queryType, config.Address);
                    }).As(queryType);
            }
        }
```

### PR DESCRIPTION
**Pull request by roryprimrose**
Closes #43

### CODE REVIEW

**Comment by canton7** [comment]
I don't want to add a gazillion new overloads to support one niche use-case. I might be persuaded to add a new overload of the non-static `For`, but let's explore other possibilities as well.

**Comment by roryprimrose** [comment]
Totally understand. What about ditching all the static type based overloads, but leave the type based plumbing. That means my caller code could still use

```
 new RestClient(baseUrl).For(type);
```

That would mean the code churn would be minimal to support this.

**Comment by roryprimrose** [comment]
Ah, I just noticed that many of the static overloads have been marked as obsolete. I added all those methods just to be consistent with the existing generic static members.

I'll remove those obsolete ones from the pull request tonight. Hopefully it will be a lot cleaner.

**Comment by roryprimrose** [comment]
The changes to RestClient are a lot cleaner now that I have removed the Obsolete members I shouldn't have added.

Do you have any suggestions for how this could be done differently?

**Comment by canton7** [comment]
I'd be happiest just overloading the non-static method. The static versions are just convenience for the common cases. I've already removed some of them to reduce the intellisense clutter (the ones which are obseleted), so I'm not too happy adding more. 

This also needs null checks, and I'd like to avoid loading the Type unless necessary (there's a reason the dictionary's keyed on a RuntimeTypeHandle). I can fix those up a lunchtime though.

**Comment by canton7** [comment]
Superceded by 3ffb4302c690f30745f3326fac72d92a0abbdc0d

**Pull request closed without merging**
