### PR TITLE
Add support for abstract classes

### PR DESCRIPTION
**Pull request by fazouane-marouane**
Hi,

First of all, thanks for this awesome project. It saved me a lot of time and saved my sanity :smile: 

I came across a situation where I needed a Repository pattern in my code. I had an IRepository interface which was implemented in two ways. The first implementation used EntityFramework (which was mainly used in an asp core project) and the second implementation used RestEase :beers: which could be used for example in a WPF application.

The problem was that I didn't want to have to duplicate code and opted for an abstract class for the RestEase implementation. Thus my PR. I added some UTs to illustrate my situation.
I hope that PRs are welcome!

Thanks,
-M

### CODE REVIEW

**Comment by canton7** [comment]
Thanks for submitting this! 

I'm only on mobile at the moment so I've only had a brief look, but I'm not seeing any checks for non-abatract methods, non-public methods, no parameterless constructors, etc. 

I also have questions as to whether this is a sensible thing to do: I'll need to have a think. With the extra edge cases it might turn out to be a reasonable maintenance burden to support a niche case. 

Could you give me a simplified example of what you were trying to do with IRepository and EF? I'm not sure I understand exactly what you're trying to achieve.

**Comment by fazouane-marouane** [comment]
Hi
I myself am on my mobile for now. I'll push an example soon as I get home. For the time being, you'll find an example which answers a part of your questions in the unit tests.

As for the rationale behind my PR, I think that the only methods that can/should be implemented by RestEase are public abstract methods of the current abstract class. I probably should have added support for protected abstract methods too just to stay consistent...

Just check the unit test to see if it answers you questions about constructors etc..

**Comment by canton7** [comment]
I've had a proper read through the unit tests.

Personally I don't think that an abstract repository class, where some methods are implemented by RestEase and some contain actual (testable) logic is a good idea. I have the following thoughts:

1. It seems unlikely that the repository and API will have the same interface. Especially with things like parent/child relationships, the API may require several calls to different endpoints to update the parent and child, whereas EF may be able to do it in one go.
2. I find it very unlikely that you'll be able to use the same models for an API and EF: they will need decorating with different attributes, and the structure is highly unlikely to be the same anyway. Therefore the `IRepository` implementation for the API is going to have to do some mapping between a generic model and a model that's specific to the API, which means that you can't have `IRepository` users directly calling a method that's been implemented by RestEase: there needs to be a mapping layer in there.
3. Your abstract `IRepository` implementation contains logic (unless it only has abstract methods, in which case you could just use an interface). In order to test it, you're going to have to subclass it and stub out the abstract methods, and that's going to be painful.

I feel that both of these points are best addressed by using composition rather than inheritance. To give you a concrete example:

```csharp
public class Model
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public interface IRepository
{
    Task<Model[]> ReadAll();
    Task<Model> ReadOne(int key);
    Task<int> Create(Model payload);
    Task Update(Model payload);
    Task Delete(int key);
}

public interface ISomeApi
{
    [Get("/Entity")]
    Task<Model[]> ReadAll();

    [Get("/Entity/{id}")]
    Task<Model> ReadOne([Path] int key);

    [Post("/Entity")]
    Task<int> Create(Model payload);
}

public class ApiRepository : IRepository
{
    private readonly ISomeApi api;

    public ApiRepository(ISomeApi api)
    {
        this.api = api;
    }

    public Task<Model[]> ReadAll() => this.api.ReadAll();
    public Task<Model> ReadOne(int key) => this.api.ReadOne(key);
    public Task<int> Create(Model payload) => this.api.Create(payload);

    public Task Update(Model payload)
    {
        return Task.CompletedTask;
    }

    public Task Delete(int id)
    {
        return Task.CompletedTask;
    }
}
```

This:

1. Separates your concerns. The API and repository will probably be different in practice, and here they're given different interfaces.
2. Gives you wriggle room. You can do mapping or other transformations inside the `ApiRepository`, or do logging, etc. You can have different models for the repository and API, which will probably be required in practice, and do mapping between them.
3. Makes `ApiRepository` easy to test.

What do you think?

**Comment by fazouane-marouane** [comment]
Hi,

Thanks for taking the time to review the PR. You're absolutely right. I guess that I didn't think it through.
I've had a very large controller which implemented CRUD for quite many entities. Same thing with the corresponding EntityFramework implementation... etc.

So I took some time to refactor the app and everything is much simpler now. So I settled with the following in the client side

```{.cs}
public interface IRestfulClient<T, TKey>
{
    [Post("")]
    Task<TKey> Create([Body]T payload);

    [Get("")]
    Task<T[]> ReadAll();

    [Get("{key}")]
    Task<T> ReadOne([Path]TKey key);

    [Put("")]
    Task Update([Body]T payload);

    [Delete("{key}")]
    Task Delete([Path]TKey key);
}
```

Thanks again and feel free to close the PR!

**Pull request closed without merging**
